# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-12 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0003_auto_20180511_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profile',
        ),
    ]
