# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0010_auto_20180528_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Instagram.Photo'),
            preserve_default=False,
        ),
    ]
